### ISSUE TITLE
Level Status

### ISSUE THREAD

**Issue by AlexDyre** [ferdinh/defcon-z#20]
## Expected Behavior
As a player, I wish to be able to view the status of the current game level, so that I can plan ahead.

## Possible Solution
A level status indicator needs to be implemented

**Comment by ferdinh** [comment]
Moved to Sprint 2.

**Comment by ferdinh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Level Status](https://trello.com/c/hNJZyZ3i/5-level-status)
