### ISSUE TITLE
Game Difficulty

### ISSUE THREAD

**Issue by AlexDyre** [ferdinh/defcon-z#28]
## Expected Behavior
Players should have at least three different difficulty levels.

## Possible Solution
Game difficulty needs to be implemented.

**Comment by ferdinh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Easy Difficulty](https://trello.com/c/4mfWWJ1p/21-easy-difficulty)

**Comment by ferdinh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Normal Difficulty](https://trello.com/c/k2MPkUnS/22-normal-difficulty)

**Comment by ferdinh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hard Difficulty](https://trello.com/c/V1RkyKF6/23-hard-difficulty)
