### ISSUE TITLE
GUI Scaling

### ISSUE THREAD

**Issue by AlexDyre** [ferdinh/defcon-z#60]
## Expected Behavior
GUI Elements should not be blurry when scaling with resolution.
GUI Elements should scale with resolution.

## Current Behavior
GUI do not scale with screen resolution. 
GUI scaling renders GUI elements blurry.

## Possible Solution
Unity 2019.1.1f1 offers UI Elements. A Highly modular UI system. Highly worth investigating.

**Comment by ferdinh** [comment]
Accidental close.

**Comment by ferdinh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scale-able GUI](https://trello.com/c/vr1s8dnj/59-scale-able-gui)
