### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by ferdinh** [ferdinh/defcon-z#89]
As a player I want to have a random or predetermined events occurring that strengthen my faction or weaken it so that I can have more challenge.

**Comment by ferdinh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Events](https://trello.com/c/sGIR4Lu0/68-events)

**Comment by NivalisSystem** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Basic enemy AI](https://trello.com/c/PEdGBwbz/70-basic-enemy-ai)
